version: '3.8'

networks:
  live-chat-network:
    driver: bridge

services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: backend_test
    environment:
      - FLASK_APP=app.py
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/chat_db
    depends_on:
      - redis
      - mongo
    networks:
      - live-chat-network
    command: ["pytest", "test_app.py"]  # Run tests when the container starts

  redis:
    image: redis:alpine
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - live-chat-network
  
  mongo:
    image: dannyben/alpine-mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=chat_db
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - live-chat-network
