version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: backend_test
    environment:
      - FLASK_APP=app.py
      - REDIS_HOST=redis
      - MONGO_URI=mongodb://mongo:27017/chat_db
    depends_on:
      - redis
      - mongo
    command: ["pytest", "test_app.py"]  # Run tests when the container starts

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=chat_db
    ports:
      - "27017:27017"
