version: '3.8'

# Network isolation
networks:
  live-chat-network:
    driver: bridge

services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
      - MONGO_URI=mongodb://${{ secrets.MONGO_INITDB_ROOT_USERNAME }}:${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}@mongo:27017/chat_db
    ports:
      - "5000:5000"  # Expose the backend server port
    networks:
      - live-chat-network
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:alpine
    container_name: redis
    environment:
      - REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
    networks:
      - live-chat-network

  mongo:
    image: dannyben/alpine-mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=chat_db
      - MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      - MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
    networks:
      - live-chat-network
