version: '3.8'

services:
  # Backend Service (Flask + Redis + MongoDB)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - REDIS_HOST=redis
      - MONGO_URI=mongodb://mongo:27017/chat_db
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongo

  # Frontend Service (React or Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  # Redis Service (for real-time data)
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  
  # MongoDB Service (for database storage)
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=chat_db
    ports:
      - "27017:27017" 
