name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-flask flask-socketio

      - name: Lint Code
        run: pylint app.py

      - name: Build and Test with Docker Compose
        run: |
          docker-compose -f compose.test.yml up --build --abort-on-container-exit
